[package]
name = "soroban-subscription"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk = { version = "22.0.0", features = [] }

[dev-dependencies]
soroban-sdk = { version = "22.0.0", features = ["testutils"] }
